### ISSUE TITLE
persistent disks are not persistent when using garden-runc v1.1.1 or v1.2.0

### ISSUE THREAD

**Issue by geofffranks** [cppforlife/bosh-warden-cpi-release#5] opened 2017-02-28 01:34 UTC
Haven't tried this on other versions of garden-runc, but at least on 1.1.1 and 1.2.0, persistent disks do not persist past the lifespan of the VM/garden container.

To reproduce:
1. Deploy a bosh-lite with garden-runc v1.1.1 or 1.2.0 as the garden backend.
2. Deploy a BOSH deployment to the bosh-lite that requires persistent disk.
3. Make changes to that persistent disk.
4. bosh recreate the VM with persistent disk
5. The persistent data is gone (expected it to persist)

Notes:
It appears that the mount point isn't being propagated to the garden container properly, and the persistent-disk writes from the container go to the `/var/vcap/warden_cpi/persistent_bind_mounts_dir/<cid>/<disk_id>` directory, rather than the device that was mounted on top of that directory. When the container is destroyed/recreated, it gets a new cid, and a new persistent_bind_mount directory.

My best guess is there is missing mount propagation that was working under garden-linux, but not present in garden-runc. When I spoke to the garden team about this, they seemed to think it was an issue with the warden-cpi.

**Comment by cppforlife** [comment] 2017-02-28 22:21
@geofffranks interesting, let me try that out locally. nothing was changed between integration with garden-linux and garden-runc.

**Comment by cppforlife** [comment] 2017-03-01 00:20
interesting... confirmed it's a problem.

**Comment by geofffranks** [comment] 2017-04-04 19:04
Any word on whether this is an issue in garden-runc or the warden-cpi? What needs to happen to resolve this?

**Comment by geofffranks** [comment] 2017-05-04 13:16
@cppforlife @julz ^^

**Comment by wayneeseguin** [comment] 2017-08-03 20:47
@cppforlife ^^ Any update on this one?

**Comment by goutamtadi1** [comment] 2017-08-11 23:07
Following this with @cjcjameson @d -- experienced this because the new recommended "bosh-lite" workflow layers on garden-runc: https://bosh.io/docs/bosh-lite#install

**Comment by luan** [comment] 2017-08-29 15:21
This has been fixed in garden-runc-release 1.9.2, will be picked up by bosh-deployment soon (see https://github.com/cloudfoundry/bosh-deployment/pull/130).

**Comment by geofffranks** [comment] 2017-08-29 22:27
\o/ thanks!

**Closed** 2017-09-29 07:45 UTC
